name: sketch
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_immutable_collections: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  ffuf_lints:
    hosted: https://pubdev.ffuf.de
    version: ^2.0.0
  # For custom lints also add
  custom_lint: ^0.5.0
flutter:

